### ISSUE TITLE
Error fetching API while retrieving market id

### ISSUE THREAD

**Issue by ricardoboss** [foo-git/rewe-discounts#10]
Followed the instructions to obtain the market ID, but the API seems to have changed:

```
FAIL: Unknown error while fetching discounts from https://shop.rewe.de/mc/api/markets-stationary/28199. Maybe a typo or the server rejected the request.
```

Accessing the URL manually ends in a 404.

**Comment by foo-git** [comment]
Confirmed, the API has changed.
Right now this affects only the retrieving of the market id via postal code.
If the market id is known (or was retrieved before the API change), the discount retrieval is not affected.
